# Project: junqo
# Description: Dockerfile for the development environment of the back-end application.

# Build stage
FROM node:22-slim AS builder

# Arguments
ARG DATABASE_HOST=db
ARG DATABASE_PORT=5432
ARG DATABASE_NAME=junqo
ARG DATABASE_USER=junqo

# Environment variables
ENV GRAPHQL_SCHEMAS_PATH=/home/app/schemas
ENV NODE_ENV=development
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USER=${DATABASE_USER}

# Create an unprivileged user
RUN useradd -ms /bin/sh app

# Set the working directory
WORKDIR /home/app/junqo_back/

# Copy source code and schema definition
COPY --chown=app ./junqo_back/ ./
COPY --chown=app ./schemas/ /home/app/schemas

# Install npm and healthcheck dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends procps curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Ensure app user owns the work directory and has permissions
RUN mkdir -p /home/app/junqo_back/dist/ && chown -R app /home/app/junqo_back/

# Use non-root user
USER app

# Install dependencies
RUN npm ci --include=dev

HEALTHCHECK --interval=5s --timeout=5s --start-period=20s --retries=5 \
    CMD curl -X POST -H "Content-Type: application/json" -d '{"query":"query{__typename}"}' http://localhost:3000/graphql || exit 1

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["sh", "-c", "npm run start:dev"]
