targets:
  $default:
    builders:
      # For more information see: https://ferrygraphql.com/docs/codegen/
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: junqo_front|lib/schemas/schema.graphql
          # schemas:
          #   - junqo_front|lib/schemas/schema2.graphql
          type_overrides:
            Email:
              name: String
            DateTime:
              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: junqo_front|lib/schemas/schema.graphql
          # schemas:
          #   - junqo_front|lib/schemas/schema2.graphql
          type_overrides:
            Email:
              name: String
            DateTime:
              name: DateTime
