# Project: junqo
# Description: Dockerfile for the development environment of the front-end application.

# Stage 1 - Install dependencies and build the app in a build environment
FROM debian:bullseye AS build-env

ARG FLUTTER_VERSION=3.35.3
ARG API_URL

# Install flutter dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    wget \
    unzip \
    xz-utils \
    libgconf-2-4 \
    gdb \
    libstdc++6 \
    libglu1-mesa \
    fonts-droid-fallback \
    lib32stdc++6 \
    python3 \
    sed \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# See https://docs.flutter.dev/release/archive to change the version
WORKDIR /usr/local/
ENV PATH="/usr/local/src/flutter/bin:${PATH}"
RUN wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz && \
    tar -xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -C src && \
    rm flutter_linux_${FLUTTER_VERSION}-stable.tar.xz && \
    git config --global --add safe.directory /usr/local/src/flutter && \
    flutter doctor -v && \
    flutter config --enable-web

# Copy files to container and build
WORKDIR /home/app/junqo_front
COPY ./junqo_front/ .

# Get dependencies (this layer will be cached if pubspec files don't change)
RUN flutter pub get

# Build the app
RUN if [ -n "$API_URL" ]; then \
    flutter build web --debug --dart-define=API_URL=$API_URL; \
    else \
    flutter build web --debug; \
    fi
RUN test -d build/web || (echo "Error when building the web app, web build not found" && exit 1)

# Clean up unnecessary files to reduce image size
RUN rm -rf /usr/local/src/flutter

# Stage 2 - Create the run-time image
FROM nginx:1.29.2-alpine

HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=5 \
    CMD curl -f http://localhost || exit 1

COPY --from=build-env /home/app/junqo_front/build/web /usr/share/nginx/html
COPY --chown=nginx:nginx ./junqo_front/nginx.conf /etc/nginx/nginx.conf
RUN test -f /etc/nginx/nginx.conf || (echo "Nginx config not found" && exit 1) && chmod 644 /etc/nginx/nginx.conf
RUN test -e /usr/share/nginx/html/flutter_service_worker.js || (echo "Error when building the web app, web build not found" && exit 1)

EXPOSE 80
