# Launch tests for the backend
name: Backend Tests

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  changes-check:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            any_changed:
              - 'junqo_back/**'
              - '.github/workflows/back-tests.yml'

  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you are using

    - name: Install dependencies
      working-directory: junqo_back
      run: npm install

    - name: Run functional tests
      env:
        BACK_ENV_FILE: "./junqo_back/exemple.env"
      working-directory: junqo_back
      run: npm test

    - name: Run e2e tests
      env:
        BACK_ENV_FILE: "./junqo_back/exemple.env"
      working-directory: junqo_back
      run: npm run test:e2e

    - name: Lint code
      working-directory: junqo_back
      run: npm run lint

  mark-tests-passed-if-no-changes:
    needs: changes-check
    if: needs.changes-check.outputs.any_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Mark tests as passed
        run: echo "No relevant changes detected - marking as passed."
